version: '3.9'



services:
  web:
    container_name: my-awesome-app-cml-prod
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '3010:3000'
      - '80:8080'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules