version: '3.9'

services:

  web:
    container_name: my-awesome-app-cml-dev

    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
      - '80:80'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules

  test:
    container_name: my-awesome-app-cml-test
    depends_on:
      - "web"
    image: my-awesome-app-cml_web
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: ["npm", "test"]

