version: '3.9'

services:

  prod-web:
    container_name: my-awesome-app-cml-aws
    # image: cmluckmann/my-awesome-app-cml:latest

    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '80:8080'