name: Build Prod Image & Deploy to Docker Hub

on:
  release:
    types: [published]
      
  
  workflow_dispatch:
    

env:
  AWS_REGION: us-east-1
  DATE_STAMP: $(date +%s)

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
          - uses: actions/checkout@v2

          - name: Env variables
            run: echo "date-stamp=${{ env.DATE_STAMP}}" >> $GITHUB_ENV
          # - name: Build the Docker image
          #   run: docker build -f Dockerfile.dev -t cmluckmann/my-awesome-app-cml:latest .
          # - name: Add "date-stamp" tag to the image.
          #   run: docker image tag cmluckmann/my-awesome-app-cml:latest cmluckmann/my-awesome-app-cml:${{ env.date-stamp}}
          # - name: Login to Docker Hub
          #   uses: docker/login-action@v1
          #   with: 
          #     username: ${{ secrets.DOCKER_USERNAME }}
          #     password: ${{ secrets.DOCKER_TOKEN}}
          # - name: Push the Docker image to Docker Hub
          #   run: docker push --all-tags cmluckmann/my-awesome-app-cml   
          - name: Configure AWS Credentials
          - uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
              aws-region: us-east-1

          - name: Generate deployment package
            run: zip -r deploy.zip . -x '*.git*'

          - name: Deploy to AWS EBS
            uses: einaregilsson/beanstalk-deploy@v20
            with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
              aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
              application_name: my-awesome-app-cml
              environment_name: Myawesomeappcml-env
              version_label: ${{ env.date-stamp }}
              region: us-east-1
              deployment_package: deploy.zip